### ISSUE TITLE
Ryan - Short Names for Actions

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digital-equity-report#79]
Create short names for actions to be used in accordian

**Comment by theryankelly** [comment]
@trust-kimberly short names added to word doc

**Comment by trust-kimberly** [comment]
Thanks, the short names work much better with the accordion format and in a header sized font

![Screen Shot 2022-03-10 at 3 10 36 PM](https://user-images.githubusercontent.com/62153141/157746549-5091f143-2b68-411b-bc51-8fb6c51f95eb.png)
![Screen Shot 2022-03-10 at 3 10 46 PM](https://user-images.githubusercontent.com/62153141/157746552-7ddc7b38-4fb3-4964-a07e-c818c60ed494.png)
